### ISSUE TITLE
 GitHub and Conda package sources for v0.11.6 don't match

### ISSUE THREAD

**Issue by davidhewitt** [conda-forge/setuptools-rust-feedstock#10]
I've had an issue reported upstream that the `conda-forge` package for `setuptools-rust` doesn't appear to contain the correct sources: https://github.com/PyO3/setuptools-rust/issues/97

I've manually verified I see the same mismatch as reported in that issue.

The PyPI download (https://files.pythonhosted.org/packages/9d/87/7d1487395ab2e1d3c101d34b8e6ed346308f45349e5cdd3101963cc1c9cd/setuptools-rust-0.11.6.tar.gz) looks correct to me, so I worry that something has gone wrong in the recipe here.

Would someone be able to look into this? Thanks!

**Comment by ocefpaf** [comment]
@davidhewitt maybe #11 fixed it. Can you check if that diff was the patch?

**Comment by davidhewitt** [comment]
It looks like that was indeed the issue. I can confirm that https://anaconda.org/conda-forge/setuptools-rust/0.11.6/download/noarch/setuptools-rust-0.11.6-pyhd8ed1ab_1.tar.bz2 matches the source in the github / pypi download. Thanks very much for the fix.
